### PR TITLE
Handle interaction of peek2 and peek3 with None-delimited groups

### LINKED ISSUE #916: syn fails to parse async fn inside `None`-delimited group
The following code (repository: https://github.com/Aaron1011/async-syn):

```rust
// src/lib.rs
use syn::ItemFn;
use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn parse_fn(_attr: TokenStream, item: TokenStream) -> TokenStream {
    syn::parse_macro_input!(item as ItemFn);
    TokenStream::new()
}

// src/main.rs
macro_rules! make_fn {
    ($input:item) => {
        #[async_syn::parse_fn]
        fn outer() {
            $input
        }
    }
}

make_fn!(async fn inner() {});

fn main() {
    println!("Hello, world!");
}
```

gives the following error:

```
error: unexpected token
  --> src/main.rs:10:16
   |
10 | make_fn!(async fn inner() {});
   |                ^^
```

I think this is caused by the way `syn` does lookahead when parsing `async fn`. The error goes away if you change `async fn inner() {}` to `fn inner() {}`

Minimized from https://github.com/rust-lang/rust/issues/78629

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #916.

### CODE REVIEW

File: src/parse.rs [hunk 1]
```diff
@@ -620,17 +620,36 @@ impl<'a> ParseBuffer<'a> {
...
         let _ = token;
-        self.cursor().skip().map_or(false, T::Token::peek)
+        peek2(self, T::Token::peek)
     }
 
     /// Looks at the third-next token in the parse stream.
     pub fn peek3<T: Peek>(&self, token: T) -> bool {
+        fn peek3(buffer: &ParseBuffer, f: fn(Cursor) -> bool) -> bool {
+            if let Some(group) = buffer.cursor().group(Delimiter::None) {
+                if group.0.skip().and_then(Cursor::skip).map_or(false, f) {
```
Comment (Aaron1011) [inline src/parse.rs:640]: Does this handle nested `None` groups?

Comment (dtolnay) [reply src/parse.rs:640]: Perhaps not, but we haven't been trying to handle arbitrary None groups in arbitrary configuration, only cases that arise in practice.
