### PR TITLE
Rust implementation of download and extract source code

### LINKED ISSUE #572: Tests that need rust-lang/rust checkout don't run on Windows
Specifically, `test_precedence::test_rustc_precedence` and `test_round_trip::test_round_trip` both call `common::clone_rust` which runs `tests/clone.sh`, which obviously doesn't work on Windows.

There are several ways this could be addressed:

- Detect Windows and fail the test with a more useful error than ``called `Result::unwrap()` on an `Err` value: Os { code: 193, kind: Other, message: "%1 is not a valid Win32 application." }``
- Detect Windows and ignore the tests (`#[cfg_attr(target_os = "windows", ignore)]`)
- Rewrite `clone.sh` using Rust
- Provide a Powershell equivalent of `clone.sh` and use that on Windows

### PR DESCRIPTION
**Pull request by AndyGauge**
Fixes #572

### CODE REVIEW

File: tests/repo/mod.rs [hunk 1]
```diff
@@ -52,7 +55,36 @@ pub fn base_dir_filter(entry: &DirEntry) -> bool {
...
+                }
+            }
+            let root_folder = zip.by_index(0).unwrap().sanitized_name();
+            let rust_path = Path::new("tests/rust");
+            if rust_path.exists() {
+                remove_dir_all(rust_path)?;
+            }
+            rename(root_folder, rust_path)?;
+            if let Ok(mut commit) = File::create(&Path::new("tests/rust/COMMIT")) {
+                commit.write_all(REVISION.as_bytes())?;
```
Comment (dtolnay) [inline tests/repo/mod.rs]: It would be simpler to use https://doc.rust-lang.org/std/fs/fn.write.html:

```rust
fs::write("tests/rust/COMMIT", REVISION)?;
```

File: tests/repo/mod.rs [hunk 2]
```diff
@@ -52,7 +55,36 @@ pub fn base_dir_filter(entry: &DirEntry) -> bool {
...
-pub fn clone_rust() {
-    let result = Command::new("tests/clone.sh").status().unwrap();
-    assert!(result.success());
+pub fn clone_rust() -> io::Result<()> {
+    if match read_to_string("tests/rust/COMMIT") {
+        Err(_) => true,
+        Ok(contents) => contents.trim() != REVISION,
+    } {
+        let url = format!("https://github.com/rust-lang/rust/archive/{}.zip", REVISION);
+        let mut tmpfile = tempfile::tempfile().unwrap();
```
Comment (dtolnay) [inline tests/repo/mod.rs]: Would it be possible to do this without saving the file to disk? These files are reasonably small.

**Comment by dtolnay** [comment]
Ping @AndyGauge &mdash; are you still planning to work more on this?

**Comment by AndyGauge** [comment]
Yes, I’ll see it through.  I’ve been overcommitted on other projects recently.

Maybe 2 weeks from now or so.

File: tests/repo/mod.rs [hunk 3]
```diff
@@ -52,7 +55,36 @@ pub fn base_dir_filter(entry: &DirEntry) -> bool {
...
 
-pub fn clone_rust() {
-    let result = Command::new("tests/clone.sh").status().unwrap();
-    assert!(result.success());
+pub fn clone_rust() -> io::Result<()> {
+    if match read_to_string("tests/rust/COMMIT") {
+        Err(_) => true,
+        Ok(contents) => contents.trim() != REVISION,
+    } {
+        let url = format!("https://github.com/rust-lang/rust/archive/{}.zip", REVISION);
```
[the remark this answers is not in the document]
Comment (AndyGauge) [reply tests/repo/mod.rs]: I incorrectly assumed tar.gz was not supported on windows, I just proved that wrong and am rewriting the PR to use tar.gz and flate crate

File: tests/repo/mod.rs (hunk 2 above)
Comment (AndyGauge) [reply tests/repo/mod.rs]: I will check on that.

Comment (AndyGauge) [reply tests/repo/mod.rs]: I haven't found a way other than memmap, which I'm not comfortable adding that much complexity.

File: tests/repo/mod.rs [hunk 4]
```diff
@@ -52,7 +55,36 @@ pub fn base_dir_filter(entry: &DirEntry) -> bool {
...
+        if let Ok(_request) = reqwest::get(url.as_str()).unwrap().copy_to(&mut tmpfile){
+            let mut zip = zip::ZipArchive::new(tmpfile).unwrap();
+            for i in 0..zip.len() {
+                let mut file = zip.by_index(i).unwrap();
+                let outpath = file.sanitized_name();
+                if file.name().ends_with('/') {
+                    create_dir_all(&outpath).unwrap()
+                }
+                else {
+                    let mut outfile = File::create(&outpath).unwrap();
```
[the remark this answers is not in the document]
Comment (AndyGauge) [reply tests/repo/mod.rs]: Most of this complexity will be removed by using flate2.

File: tests/repo/mod.rs [hunk 5]
```diff
@@ -52,7 +55,36 @@ pub fn base_dir_filter(entry: &DirEntry) -> bool {
...
-    let result = Command::new("tests/clone.sh").status().unwrap();
-    assert!(result.success());
+pub fn clone_rust() -> io::Result<()> {
+    if match read_to_string("tests/rust/COMMIT") {
+        Err(_) => true,
+        Ok(contents) => contents.trim() != REVISION,
+    } {
+        let url = format!("https://github.com/rust-lang/rust/archive/{}.zip", REVISION);
+        let mut tmpfile = tempfile::tempfile().unwrap();
+        if let Ok(_request) = reqwest::get(url.as_str()).unwrap().copy_to(&mut tmpfile){
```
[the remark this answers is not in the document]
Comment (AndyGauge) [reply tests/repo/mod.rs]: I'm rewriting the return type to Box<dyn std::error::Error>.  I'm `.expect`ing the result anyway so it shouldn't have a major impact, but at least the errors will make it to the caller.

**Comment by dtolnay** [comment]
Thanks -- I removed the tempfile stuff in 02c6857e1bf2df78cd1e9f25fbb1d5fcfa3fdce0, we don't need the tar.gz written to the filesystem or memmap.
